PREFS___board___upload___speed=1000000
PREFS___board___build___f_cpu=96000000L
PREFS___board___upload___maximum_size=27648
PREFS___board___name=ZPUino on Papilio One (500) board
PREFS___board___build___extraCflags=-D__ZPUINO_PAPILIO_ONE__ -D__S3E_500__ -nostartfiles
PREFS___board___upload___protocol=zpuino-serial
PREFS___board___build___core=zpuino
COREPATH=$(ZPULOGSK)/lib
AVRPATH=
BUILDPATH=$(PWD)
REVISION=22
